# Install git hooks — generated by Nebula
$ErrorActionPreference = "Stop"

Write-Host "Installing git hooks..."

if (-not (Test-Path ".git")) {
  Write-Host "Error: not a git repository" -ForegroundColor Red
  exit 1
}

Copy-Item "hooks/pre-commit.ps1" ".git/hooks/pre-commit" -Force; Write-Host "  Installed pre-commit"
Copy-Item "hooks/pre-push.ps1" ".git/hooks/pre-push" -Force; Write-Host "  Installed pre-push"

Write-Host "Done!"
