# Git pre-push hook — generated by Nebula
$ErrorActionPreference = "Stop"

Write-Host "Running pre-push checks..."

#!/bin/bash
echo 'Running pre-push checks...'
if [ -f 'package.json' ]; then
  if grep -q '"test"' package.json; then
    npm test
    if [ $? -ne 0 ]; then
      echo 'Tests failed. Please fix before pushing.'
      exit 1
    fi
  fi
fi
echo 'Pre-push checks passed!'
exit 0
